### ISSUE TITLE
ciq_config -w issue

### ISSUE THREAD

**Issue by mcmorgan27** [sandiegodata/cityiq#2]
Running py 3.8.2 on ubuntu 18.04
using the readme to get started.  This is an error I'm getting on the ciq_config -w command.

(sherpa) mcmorgan@heisenberg:~/projects/projects.geo/opensd$ ciq_config -w
Traceback (most recent call last):
  File "/home/mcmorgan/anaconda3/envs/sherpa/bin/ciq_config", line 8, in <module>
    sys.exit(run())
  File "/home/mcmorgan/anaconda3/envs/sherpa/lib/python3.8/site-packages/cityiq/cli/config.py", line 105, in run
    main(sys.argv[1:])
  File "/home/mcmorgan/anaconda3/envs/sherpa/lib/python3.8/site-packages/cityiq/cli/config.py", line 64, in main
    config = Config()
  File "/home/mcmorgan/anaconda3/envs/sherpa/lib/python3.8/site-packages/cityiq/config.py", line 55, in __init__
    self._config = self._load_config()
  File "/home/mcmorgan/anaconda3/envs/sherpa/lib/python3.8/site-packages/cityiq/config.py", line 79, in _load_config
    raise ConfigurationError(f"Didn't find a config file in paths: {self._paths}")
cityiq.exceptions.ConfigurationError: Didn't find a config file in paths: [PosixPath('/home/mcmorgan/projects/projects.geo/opensd/.city-iq.yaml'), PosixPath('/home/mcmorgan/projects/projects.geo/opensd/city-iq.yaml'), PosixPath('/home/mcmorgan/.city-iq.yaml')]

Any quick fix before I start debugging?

Thanks.

**Comment by ericbusboom** [comment]
Well ... that's not right. What version are you running on ?

**Comment by mcmorgan27** [comment]
python 3.8.2
ubuntu 18.04

**Comment by ericbusboom** [comment]
For cityiq module: run `ciq_config --version`

**Comment by mcmorgan27** [comment]
(sherpa) mcmorgan@heisenberg:~/projects/projects.geo/opensd$ ciq_config
--version
cityiq 0.1.5

**Comment by ericbusboom** [comment]
Ok, that's the latest, and I just did a fresh install of cityiq to Python 3.8 on Mac/Anaconda and ciq_config worked ok. I'll try ubuntu 18.04 next.

**Comment by ericbusboom** [comment]
It was a dumb bug that didn't throw an error in my test environment. It's fixed in github, so you should be able to install the fix with: 

pip install -U git+https://github.com/sandiegodata/cityiq.git

**Comment by mcmorgan27** [comment]
It works.

Thanks.
